pepname[0] = "NO PALETTE \nIM NOT GONNA MAKE A PISS JOKE";
pepname[1] = "DEFAULT \nSO BLAND AND STUPID";
pepname[2] = "SAGE BLUE \nIS THIS SOME KIND OF SAGE DEMO";
pepname[3] = "VERSION ONE \nHI IM JOHN MEGAKILL";
pepname[4] = "PORCUPINE PURPLE \nI RIPPED OFF SNICK'S QUILS FOR THIS";
pepname[5] = "BLOOD RAGH! BLOODY RAAGH! \nMURDER  EVERY 1 U KNOW!";
pepname[6] = "GOLD \nIT'S ACTUALLY CHEESE";
pepname[7] = "MISTER LOG \nIM SO STUMPED, WHAT DO THESE LOGS MEAN?";
pepname[8] = "BLACK \nREALLY JUST BLACK PEPPINO";
pepname[9] = "DISCORD \nWHAT IS WRONG WITH YOU? WHY ARE YOU BLUE?";
pepname[10] = "THE ROARING \nTHINGS TOOK QUITE A WEIRD ROUTE...";
pepname[11] = "URANIUM \nSUGGESTED BY DARTHOLEMEW OR SMTH IDK";
pepname[12] = "THE SCRATCH CAT \nSUGGESTED BY CRAZY DOE";
pepname[13] = "HARD-WEEN \nSUGGESTED BY BETCH";
pepname[14] = "COLORS AND ELECTRICITY \nI WANT TO KNOW ALL SORTS OF COLOURS";

if (obj_player.image_blend == c_red)
    pepname[14] = "COLORS AND ELECTRICITY \nI WANT TO BECOME PURE!!!";

pepname[15] = "VEGGIE VANITY \nI'D LOVE TO SEE YOU EAT A GRAPE!";
pepname[16] = "TETO \nSOMEDAY, I'LL BE A VOCALOID TOO!";
pepname[17] = "PURSUER \nALL OF IT'S PREY SHALL BE PURSUED";
pepname[18] = "RESPONSIBILITY \n👀";
noisename[1] = "NO PALETTE \nUNLOCKED  BY BEING THE NOISE!";
noisename[2] = "HARDOWEEN \nI HATE THIS FUCKING DEMO";
noisename[3] = "MILK COATED \nIS THIS A JOKE???";
noisename[4] = "PORCUPINE \nSKIN WALKER";
noisename[5] = "GRUNCH \nOMG IT'S THE CRUNCH!";
noisename[6] = "REVERSEOWEEN \nIM IN LOVE WITH THIS DEMO!";
noisename[7] = "BLUE \nYOU'RE SO BLUU, DUDE";
noisename[8] = "GOISE \nI DON'T THINK YOULL KNOW THE REFERENCE";
noisename[9] = "VANITY \nSTILL PREYING ON A BUTCHERS VEIN";
noisename[10] = "STATIC \nTHIS IS HOW IT SHOULD BE!";
