font = font_add_sprite_ext(spr_font, "ABCDEFGHIJKLMNOPQRSTUVWXYZ!.1234567890:", 1, 0);
draw_set_font(font);
draw_set_halign(fa_center);
draw_text_colour(480, creditY + 560, "CREDITS", c_white, c_white, c_white, c_white, 1);
draw_text_colour(480, creditY + 800, "MATKRUTOY \nMADE PRETTY MUCH EVERYTHING", c_white, c_white, c_white, c_white, 1);
draw_text_colour(480, creditY + 900, "YAN THE YANNER \nMADE A LOT OF SPRITES", c_white, c_white, c_white, c_white, 1);
draw_text_colour(480, creditY + 1000, "KRY \nALSO MADE SOME SPRITES", c_white, c_white, c_white, c_white, 1);
draw_text_colour(480, creditY + 1100, "KIWUMA \nPLAYTESTER", c_white, c_white, c_white, c_white, 1);
draw_text_colour(480, creditY + 1200, "SILLYARTEMIS I THINK?? \nPLAYTESTER", c_white, c_white, c_white, c_white, 1);
draw_text_colour(480, creditY + 1600, "THANK YOU PLAYING THE DEMO", c_white, c_white, c_white, c_white, 1);
