font = font_add_sprite_ext(global.fontspritee, global.fontcharacterss, 1, 0);
draw_set_font(font);
draw_set_halign(fa_center);
draw_set_color(c_white);
draw_text_colour(480, creditY + 560, "CREDITS", c_white, c_white, c_white, c_white, 1);
draw_text_colour(480, creditY + 700, "MARKRUTO \nMADE PRETTY MUCH EVERYTHING", c_orange, c_orange, c_white, c_white, 1);
draw_text_colour(480, creditY + 800, "YAN THE YANNER \nMADE A LOT OF SPRITES", c_white, c_white, c_white, c_white, 1);
draw_text_colour(480, creditY + 900, ". \nALSO MADE SOME SPRITES", c_white, c_white, c_white, c_white, 1);
draw_text_colour(480, creditY + 1000, "KIWUMA \nTILED, VOICE ACTED AND I MAED HER CODE", c_purple, c_purple, c_white, c_white, 1);
draw_text_colour(480, creditY + 1100, "SILLYARTEMIS I THINK?? \nPLAYTESTER", c_white, c_white, c_white, c_white, 1);
draw_text_colour(480, creditY + 1200, "GROPUS \nMADE LESS SPRITES BUT STILL COOL", c_white, c_white, c_white, c_white, 1);
draw_text_colour(480, creditY + 1300, "PTBB AND PTS GUY \nSPRITER", c_purple, c_white, c_purple, c_white, 1);
draw_text_colour(480, creditY + 1400, "SUSIE \nCOWMPOSER", c_white, c_white, c_white, c_white, 1);
draw_text_colour(480, creditY + 1500, "SLOP \nGAVE ME PERMISSION TO USE LEPPER", c_lime, c_lime, c_lime, c_lime, 1);
draw_text_colour(480, creditY + 1600, "GOOBER \nPLAYTESTER", c_white, c_white, c_white, c_white, 1);
draw_text_colour(480, creditY + 1700, "AUN \nSPRITER!!!", c_white, c_white, c_white, c_white, 1);
draw_text_colour(480, creditY + 1800, "ARTYOM \nSPRITER!!!", c_white, c_white, c_white, c_white, 1);
draw_text_colour(480, creditY + 1900, "RE-ANIMGUY \nPLAYTESTER", c_white, c_yellow, c_white, c_yellow, 1);
draw_text_colour(480, creditY + 2000, "DOUG3P \nCOWWMPOSER!!", c_lime, c_lime, c_white, c_white, 1);
draw_text_colour(480, creditY + 2100, "THELOSER \nPLAYTESTER AND MAKES DECOMPS IDK", c_lime, c_lime, c_white, c_white, 1);
draw_text_colour(480, creditY + 2300, "AND THANK YOU PLAYING THE DEMO!", c_white, c_white, c_white, c_white, 1);
var gkgk = "...................................................................................................";
draw_text_colour(480, creditY + 2400, "REFRENCED CONTENT CREDITS", c_white, c_white, c_white, c_white, 1);
draw_text_colour(480, creditY + 2540, "FLAVOR FOLEY \nMADE STATIC AND BUTCHERS VANITY", c_white, c_white, c_white, c_white, 1);
draw_text_colour(480, creditY + 2640, "GOOGIFLOOP \nMADE VEGGIE VANITY", c_white, c_white, c_white, c_white, 1);
draw_text_colour(480, creditY + 2740, "DIE OF DEATH'S TEAM \nMADE PURSUER", c_white, c_white, c_white, c_white, 1);
draw_text_colour(480, creditY + 2840, "NOT CREDITING THE YAAI GUY CUZ I HATE HIM", c_white, c_white, c_white, c_white, 1);
draw_sprite(blamekiwuma, -1, 480, creditY + 3020);
var tip = "add 280 to the last y cordinate for kiwuma blaming activites if you modified this even slightly";
