scr_initinput();
global.playingsnickchallenge = 0;
global.loadedthefuckingrankspritesandshi = 0;
global.levelrestartamount = 0;
staticafterimg = 0;
tpcd = 0;
tph = 0;
tpv = 0;
tptimes = 0;
yscaleplus = 0;
xscaleplus = 0;
ervilvariable = 0;
ini_open("SGOUTDATA new.ini");
hallucinationtimer = -1;
global.unlockedidiot = ini_read_real("unlocks", "idiot", 0);
global.strechmulti = ini_read_real("OPTIONEZ", "strechmulti", 1);
global.instantR = ini_read_real("OPTIONEZ", "instantR", 0);
global.lamepalettes = ini_read_real("OPTIONEZ", "lamepalettes", 0);
global.showmaskorhitbox = ini_read_real("OPTIONEZ", "hitboxes", 0);
global.hallucination = -99999999999;
global.panicbg = 0;
global.panicdebriseffect = ini_read_real("OPTIONEZ", "panicbg", 1);
global.maxwave = 0;
global.wave = 0;
global.pizdec = ini_read_real("OPTIONEZ", "pizdec", 0);
global.butchermus = ini_read_real("OPTIONEZ", "butchermus", 0);
global.uniquecollects = 0;
global.fontspritee = ini_read_string("OPTIONEZ", "fontsprite", 859);
global.fontcharacterss = ini_read_string("OPTIONEZ", "fontcharacters", "ABCDEFGHIJKLMNOPQRSTUVWXYZ!.1234567890:👀");
global.hurttimes = 0;
global.climbstairss = ini_read_real("OPTIONEZ", "climbstairs", 0);
global.globalzoom = ini_read_real("OPTIONEZ", "zoom", 1);
evilvar = 0;
thebeatvol = 0;
debug = 0;
mach4flame = 0;
clothes = 1601;
global.goboogers = 1;
global.karatesounds = ini_read_real("OPTIONEZ", "karatesounds", 0);
global.hasthetreasure = 0;
painscream = 158;
thebeat = 155;
pepperplay = 0;
breakdancing = -1;
updash = 0;
global.supersecretsfound = 0;
global.hitstun = 0;
tauntstoredvsp = 0;
tauntstoredhsp = 0;
superframe = 0;
global.devilkin = 1;
global.audiosfxvol = 1;
global.audiomusvol = 1;
global.audiomusbreakdancevol = 1;
global.gremlinpersonality = ini_read_real("OPTIONEZ", "gremlinperson", 0);
global.supertaunt = ini_read_real("OPTIONEZ", "Staunt", 2);
superdown = 0;
global.difficulty = 0;
global.pizzafacechasestyle = ini_read_real("OPTIONEZ", "PFchasestyle", 0);
global.peakcancel = ini_read_real("OPTIONEZ", "peakcancel", 0);
global.prank = 0;
supertaunts = 1;
killstillsuper = 0;
dir = image_xscale;
blur = 2;
mach2jumpguy = 0;
jumpsound = sfx_jump;
mach1sound = sfx_mach1;
mach2sound = sfx_mach2;
mach3sound = sfx_mach3;
mach4sound = sfx_mach4;
machturnsound = sfx_break;
machslidesound = sfx_machslideboost;
superjumpsound = sfx_superjumprelease;
superjumpholdsound = sfx_superjumphold;
superjumpprepsound = sfx_superjumpprep;
global.attackstyle = ini_read_real("OPTIONEZ", "attackstyle", 0);
global.attackstyleP = ini_read_real("OPTIONEZ", "attackstyleP", -1);
global.attackstyleN = ini_read_real("OPTIONEZ", "attackstyleN", -1);
global.attackstyleS = ini_read_real("OPTIONEZ", "attackstyleS", -1);
global.attackstyleR = ini_read_real("OPTIONEZ", "attackstyleR", -1);
global.attackstyleV = ini_read_real("OPTIONEZ", "attackstyleV", -1);
global.attackstyle2 = ini_read_real("OPTIONEZ", "attackstyle2", 0);
global.attackstyleP2 = ini_read_real("OPTIONEZ", "attackstyleP2", -1);
global.attackstyleN2 = ini_read_real("OPTIONEZ", "attackstyleN2", -1);
global.attackstyleS2 = ini_read_real("OPTIONEZ", "attackstyleS2", -1);
global.attackstyleR2 = ini_read_real("OPTIONEZ", "attackstyleR2", -1);
global.attackstyleV2 = ini_read_real("OPTIONEZ", "attackstyleV2", -1);
global.coolsnick = ini_read_real("OPTIONEZ", "coolsnick", 0);
global.coolsnick = 0;
global.deathmode = 0;
global.draintime = 0;
global.lowgrav = 0;
global.saveroom = ds_list_create();
airbone = 0;
enemiesswallowed = 0;
squished = 0;
afterimage = 5;
grav = 0.5;
hsp = 0;
vsp = 0;
global.playerhealth = 5;
xscale = 1;
yscale = 1;
facehurt = 1;
steppy = 0;
depth = -7;
movespeed = 19;
jumpstop = 0;
visible = true;
state = states.titlescreen;
jumpAnim = 1;
landAnim = 0;
machslideAnim = 0;
moveAnim = 1;
stopAnim = 1;
crouchslideAnim = 1;
crouchAnim = 1;
machhitAnim = 0;
stompAnim = 0;
inv_frames = 0;
hurted = 0;
autodash = 0;
mach2 = 0;
input_buffer_jump = 8;
input_buffer_secondjump = 8;
input_buffer_highjump = 8;
player_x = x;
player_y = y;
targetRoom = Realtitlescreen;
targetDoor = "A";
flash = 0;
global.key_inv = 0;
global.shroomfollow = 0;
global.cheesefollow = 0;
global.tomatofollow = 0;
global.sausagefollow = 0;
global.pineapplefollow = 0;
global.keyget = 0;
global.collect = 0;
global.treasure = 0;
global.combo = 0;
global.combotime = 0;
global.combopause = 0;
global.combodropped = 0;
global.pizzacoin = 0;
global.toppintotal = 1;
global.hit = 0;
global.baddieroom = ds_list_create();
global.escbaddieroom = ds_list_create();
global.gotshotgun = 0;
global.gotsaw = 0;
key_particles = 0;
barrel = 0;
bounce = 0;
a = 0;
idle = 0;
attacking = 0;
slamming = 0;
superslam = 0;
grounded = 1;
grinding = 0;
machpunchAnim = 0;
punch = 0;
machfreefall = 0;
shoot = 1;
instakillmove = 0;
windingAnim = 0;
facestompAnim = 0;
ladderbuffer = 0;
toomuchalarm1 = 0;
toomuchalarm2 = 0;
idleanim = 0;
momemtum = 0;
cutscene = 0;
grabbing = 0;
dir = xscale;
shotgunAnim = 0;
goingdownslope = 0;
goingupslope = 0;
fallinganimation = 0;
bombpeptimer = 100;
suplexmove = 0;
suplexhavetomash = 0;
anger = 0;
angry = 0;
baddiegrabbedID = 0;
character = "P";
scr_characterspr();
paletteselect = ini_read_real("palette", "Ppal", 1);
global.panic = 0;
global.snickchallenge = 0;
colorchange = 0;
treasure_x = 0;
treasure_y = 0;
treasure_room = 0;
wallspeed = 0;
spr_palette = spr_peppalette;
tauntstoredstate = states.normal;
tauntstoredmovespeed = 6;
tauntstoredsprite = spr_player_idle;
taunttimer = 20;
global.golfhit = 0;
ini_close();
ini_open("SGOUTsaveData.ini");
global.option_fullscreen = ini_read_real("Option", "fullscreen", 1);
global.option_resolution = ini_read_real("Option", "resolution", 1);
ini_close();

if (global.option_fullscreen == 0)
    window_set_fullscreen(true);

if (global.option_fullscreen == 1)
    window_set_fullscreen(false);

if (global.option_resolution == 0)
    window_set_size(480, 270);

if (global.option_resolution == 1)
    window_set_size(960, 540);

if (global.option_resolution == 2)
    window_set_size(1920, 1080);

backtohubstartx = x;
backtohubstarty = y;
backtohubroom = Realtitlescreen;
global.style = 0;
slapcharge = 0;
slaphand = 1;
slapbuffer = 8;
slapflash = 0;
freefallsmash = 0;
costumercutscenetimer = 0;
heavy = 0;
lastroom_x = 0;
lastroom_y = 0;
lastroom = Realtitlescreen;
hallway = 0;
hallwaydirection = 0;
box = 0;
roomstartx = 0;
roomstarty = 0;
global.secretfound = 0;
global.shotgunammo = 0;
swingdingbuffer = 0;
lastmove = 0;
backupweapon = 0;
ini_open("SGOUTsaveData.ini");

if (!ini_section_exists("SAGE2019"))
{
    ini_write_string("SAGE2019", "shotgunsnick", 0);
    ini_write_string("SAGE2019", "dungeonbackup", 0);
    ini_write_string("SAGE2019", "srank", 0);
    ini_write_string("SAGE2019", "snicksrank", 0);
    ini_write_string("SAGE2019", "combo10", 0);
    ini_write_string("SAGE2019", "secret", 0);
    ini_write_string("SAGE2019", "knight", 0);
    ini_write_string("SAGE2019", "toppin", 0);
    ini_write_string("SAGE2019", "treasure", 0);
}

if (!ini_section_exists("SAGE2025"))
{
    ini_write_string("SAGE2025", "overkill", 0);
    ini_write_string("SAGE2025", "12uniques", 0);
    ini_write_string("SAGE2025", "pizzaparry", 0);
}

global.SAGEshotgunsnick = ini_read_string("SAGE2019", "shotgunsnick", 0);
global.SAGEshotgunsnicknumber = 0;
global.SAGEdungeonbackup = ini_read_string("SAGE2019", "dungeonbackup", 0);
global.SAGEsrank = ini_read_string("SAGE2019", "srank", 0);
global.SAGEsnicksrank = ini_read_string("SAGE2019", "snicksrank", 0);
global.SAGEcombo10 = ini_read_string("SAGE2019", "combo10", 0);
global.SAGEsecret = ini_read_string("SAGE2019", "secret", 0);
global.SAGEknight = ini_read_string("SAGE2019", "knight", 0);
global.SAGEknighttaken = 0;
global.SAGEtoppin = ini_read_string("SAGE2019", "toppin", 0);
global.SAGEtreasure = ini_read_string("SAGE2019", "treasure", 0);
global.SAGEoverkill = ini_read_string("SAGE2025", "overkill", 0);
global.SAGE12uniques = ini_read_string("SAGE2025", "12uniques", 0);
global.SAGEpizzaparry = ini_read_string("SAGE2025", "pizzaparry", 0);
ini_close();
scr_sgoutsaves();
ini_open("SGOUTDATA new.ini");
global.audiosfxvol = ini_read_real("the 🎶", "sfx", 1);
global.audiomusvol = ini_read_real("the 🎶", "mus", 1);
global.audiomusbreakdancevol = ini_read_real("the 🎶", "musbreakdance", 1);
ini_write_real("OPTIONEZ", "panicbg", global.panicbg);
ini_write_real("OPTIONEZ", "pizdec", global.pizdec);
ini_write_real("OPTIONEZ", "fontsprite", global.fontspritee);
ini_write_string("OPTIONEZ", "fontcharacters", global.fontcharacterss);
ini_write_real("OPTIONEZ", "climbstairs", global.climbstairss);
ini_write_real("OPTIONEZ", "zoom", global.globalzoom);
ini_write_real("OPTIONEZ", "karatesounds", global.karatesounds);
ini_write_real("OPTIONEZ", "gremlinperson", global.gremlinpersonality);
ini_write_real("OPTIONEZ", "Staunt", global.supertaunt);
ini_write_real("OPTIONEZ", "PFchasestyle", global.pizzafacechasestyle);
ini_write_real("OPTIONEZ", "peakcancel", global.peakcancel);
ini_write_real("OPTIONEZ", "attackstyle", global.attackstyle);
ini_write_real("OPTIONEZ", "attackstyleP", global.attackstyleP);
ini_write_real("OPTIONEZ", "attackstyleN", global.attackstyleN);
ini_write_real("OPTIONEZ", "attackstyleS", global.attackstyleS);
ini_write_real("OPTIONEZ", "attackstyleR", global.attackstyleR);
ini_write_real("OPTIONEZ", "attackstyleV", global.attackstyleV);
ini_write_real("OPTIONEZ", "attackstyle2", global.attackstyle2);
ini_write_real("OPTIONEZ", "attackstyleP2", global.attackstyleP2);
ini_write_real("OPTIONEZ", "attackstyleN2", global.attackstyleN2);
ini_write_real("OPTIONEZ", "attackstyleS2", global.attackstyleS2);
ini_write_real("OPTIONEZ", "attackstyleR2", global.attackstyleR2);
ini_write_real("OPTIONEZ", "attackstyleV2", global.attackstyleV2);
ini_write_real("OPTIONEZ", "coolsnick", global.coolsnick);
ini_close();
stickpressed = 0;
